export { default as JSONParse } from "./JSONParse";
export { default as JSONStringify } from "./JSONStringify";
export { default as ToString } from "./OtherToString";
export { default as StringCompare } from "./StringCompare";
export { default as StringConcatenate } from "./StringConcatenate";
export { default as StringContains } from "./StringContains";
export { default as StringSplit } from "./StringSplit";
export { default as StringTemplate } from "./StringTemplate";
export { default as StringToFixed } from "./StringToFixed";
export { default as StringToTable } from "./StringToTable";
export { default as StringToUpperCase } from "./StringToUpperCase";
import { install } from "./install";
export default install;